### PR TITLE
Remove y from log det jac

### PR DESCRIPTION
**Pull request by feynmanliang**
I don't think `y` affects the jacobian

---
This change is [Reviewable](https://reviewable.io/reviews/stefanwebb/simplex/4)

### CODE REVIEW

**Comment by feynmanliang** [comment]
Whoops committed to master >.<

**Comment by stefanwebb** [comment]
https://github.com/pytorch/pytorch/blob/master/torch/distributions/transforms.py#L253

**Comment by stefanwebb** [comment]
We need to leave the y in log_det_abs_J since it is used to form the inverse of a bijection automatically. See this line:

https://github.com/pytorch/pytorch/blob/master/torch/distributions/transforms.py#L253

**Comment by feynmanliang** [comment]
I don't understand the API in Pytorch; are we required to have both `x` and
`y = transform(x)` before we can issue a call to `log_abs_det_jac(x,y)`?

**Comment by fritzo** [comment]
@feynmanliang here is some explanation, which I've added to the [original design doc](https://docs.google.com/document/d/1wnABg0cdyaVMr-Xqz_brHBwnPJuzTeSk3Oqko2HHSfE/edit#heading=h.viz1b8lempp1) for posterity:

We ended up implementing a Transform class, which may or may not be bijective, but should at least satisfy the pseudoinverse equations `t(t.inv(t(x))) = t(x)` and `t.inv(t(t.inv(y))) = t.inv(y)`. Like Distributions, Transforms are immutable, thereby simplifying cache consistency when using mechanisms like `@lazy_property`. Transforms implement a pair of low-level methods `._call()` and `._inv_call()` for forward and backward transforms. The `._call()` method is accessible by a generic `Transform.__call__()` method. The `._inv_call()` method is accessed by a generic .inv method which wraps the transform in an `InverseTransform`; this is advantageous in that both t and t.inv can provide rich metadata about their input and output shapes and domains, and consumers need not distinguish between transforms and their inverses. To ensure `InverseTransform` is generic, we use the signature `.log_abs_det_jacobian(x,y)` for change of measure; this allows the simple implementation
```py
class InverseTransform(Transform):
    def log_abs_det_jacobian(self, x, y):
        return -self._transform.log_abs_det_jacobian(y, x)
```
Additionally this allows transforms to choose whether to use x or y or both to compute the change of measure; in all known use cases both x and y have already been computed; in cases when `log_abs_det_jacobian` can be accumulated during ._call() or `._inv_call()`, those intermediates can be cached and validate with the x and y values provided to `.log_abs_det_jacobian()`.

**Comment by feynmanliang** [comment]
Thanks for the explanation 👍 

I don't think I fully appreciate the relaxation to pseudo-inverses; for the pinv to be a (non-multivalued-)function though we still need these transforms to be injective right (so if we just restrict the codomain to the range of the transform then it's a bijection again)? FWIW tfp has some [custom handling for non-injective transforms](https://www.tensorflow.org/probability/api_docs/python/tfp/bijectors/Bijector).

If x and y are already computed in all known use cases (presumably from calling `t.forward()`), isn't it possible from caching to make `InverseTransform(t).log_abs_det_jacobian(x) = -t.log_abs_det_jacobian(t.inv(x))` and `InverseTransform(t).log_abs_det_jacobian(x, y) = -t.log_abs_det_jacobian(x, y)` have equivalent run-time costs modulo cache evictions? I agree the `InverseTransform` abstraction is advantageous, but I'm not seeing why the second argument is absolutely necessary (especially if it is in 1-1 with the first argument, and in all known use cases calling `forward` / `inv` would be a cache hit).

**Comment by fritzo** [comment]
> pseudo-inverse

We explicitly allowed non-injectivity for `Transform` objects, for example the constant transform `lambda x: 0.` with pseudoinverse `lambda y: 0.` is allowed for real domain = codomain. More practically we allowed the non-injective normalize transform from positive reals to the simplex `lambda x: x / x.sum(-1, True)`, whose pseudoinverse is the non-surjective identity embedding. Of course the simplex library will need to assume bijectivity for flows.

> isn't is possible from caching...

Yeah I guess you're right, we could achieve either interface via caching. I did find the `(x,y)` form worked out well, for example it allows a purely functional (cache-oblivious) implementation of `InverseTransform`'s and `PowerTransform`'s change of measure:
```py
class PowerTransform(Transform):
    def log_abs_det_jacobian(self, x, y):
        return (self.exponent * y / x).abs().log()  # <-- notice this uses both x and y
```

**Comment by feynmanliang** [comment]
Perhaps this is a bug then?
```python
import torch.distributions as dist
d = dist.TransformedDistribution(
    dist.Uniform(0, 1),
    [dist.transforms.AffineTransform(loc=0, scale=0)]
)
d.log_prob(1.0)
```
yields
```

ZeroDivisionErrorTraceback (most recent call last)
<ipython-input-9-a993a7bf3d76> in <module>
      4     [dist.transforms.AffineTransform(loc=0, scale=0)]
      5 )
----> 6 d.log_prob(1)

/opt/conda/lib/python3.8/site-packages/torch/distributions/transformed_distribution.py in log_prob(self, value)
    109         y = value
    110         for transform in reversed(self.transforms):
--> 111             x = transform.inv(y)
    112             log_prob = log_prob - _sum_rightmost(transform.log_abs_det_jacobian(x, y),
    113                                                  event_dim - transform.event_dim)

/opt/conda/lib/python3.8/site-packages/torch/distributions/transforms.py in __call__(self, x)
    217 
    218     def __call__(self, x):
--> 219         return self._inv._inv_call(x)
    220 
    221     def log_abs_det_jacobian(self, x, y):

/opt/conda/lib/python3.8/site-packages/torch/distributions/transforms.py in _inv_call(self, y)
    145         """
    146         if self._cache_size == 0:
--> 147             return self._inverse(y)
    148         x_old, y_old = self._cached_x_y
    149         if y is y_old:

/opt/conda/lib/python3.8/site-packages/torch/distributions/transforms.py in _inverse(self, y)
    509 
    510     def _inverse(self, y):
--> 511         return (y - self.loc) / self.scale
    512 
    513     def log_abs_det_jacobian(self, x, y):

ZeroDivisionError: division by zero
```
The `log_abs_det_jacobian` is also `log(0)` for this case. More generally; isn't the constant `lambda x: 0` transform of a distribution the delta measure at 0, so implementing this `TransformedDistribution` requires testing for floating point equality? 

The `PowerTransform` is cute, but I think `(self.exponent * x**(self.exponent - 1)).abs().log()` and `(self.exponent * self(x) / x).abs().log()` are both ways to avoid using `y` (with the latter benefitting from caching)?

**Pull request closed without merging**
